
export const FETCH_TASK_REQUEST = 'FETCH_TASK_REQUEST'
export const FETCH_TASK_SUCCESS = "FETCH_TASK_SUCCESS";
export const FETCH_TASK_FAILURE = "FETCH_TASK_FAILURE";

export const ADD_TASK = "ADD_TASK";
export const DELETE_TASK = "DELETE_TASK";

export const TOGGLE_TASK_COMPLETED = "TOGGLE_TASK_COMPLETED"